version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - eigakan-external
networks:
  eigakan-external:
    external: true 
